<%@ page contentType="text/html;charset=GBK" pageEncoding="GBK"
	language="java"%>
<%
	response.reset();
	response.setContentType("application/vnd.ms-excel;charset=GBK");
%>
<html>
	<head>
		<title></title>
		<script src="${rc.contextPath}/js/main.js"></script>
		<script language="javascript">
			window.onresize = function() {
				setCenter(4,27);
			}
			window.onload = function() {
				setCenter(4,27);
				changeRow_color("tab");
			}
		</script>
	</head>
	<body>
		<table cellpadding="0" cellspacing="0" border="1" style="margin-left: 5px;">
			<tr>
				<td>
					<table border="1" cellpadding="0" cellspacing="0"	class="tableborder1">
						<tr>
							<th>
								序号
							</th>
							<th colspan="3">
								评价指标
							</th>
							<th>
								月度指标
							</th>
							<th>
								单位（%）
							</th>
							<th>
								指标值计算公式
							</th>
							<th>
								指标单位
							</th>
							<th>
								得分计算公式
							</th>
							<th>
								得分
							</th>
						</tr>
						<tr>
							<td rowspan="5">
							</td>
							<td rowspan="5">
								1
							</td>
							<td rowspan="5">
								计费财务
							</td>
							<td colspan="2">
								本月计费核查差错率
							</td>
							<td>
								指标值
							</td>
							<td>
								单位值
							</td>
							<td>
								指标值计算公式1
							</td>
							<td>
								指标单位1
							</td>
							<td>
								得分计算公式1
							</td>
							<td>
								100
							</td>
						</tr>
						<tr>
							<td colspan="2">
								本月计费准确性核查覆盖率
							</td>
							<td>
								指标值
							</td>
							<td>
								单位值
							</td>
							<td>
								指标值计算公式3
							</td>
							<td>
								指标单位3
							</td>
							<td>
								得分计算公式3
							</td>
							<td>
								100
							</td>
						</tr>
						<tr>
							<td colspan="2">
								计费参数配置准确率（小区、边界漫游等）
							</td>
							<td>
								指标值
							</td>
							<td>
								单位值
							</td>
							<td>
								指标值计算公式4
							</td>
							<td>
								指标单位4
							</td>
							<td>
								得分计算公式4
							</td>
							<td>
								100
							</td>
						</tr>
						<tr>
							<td rowspan="2">
								计费调账率
							</td>
							<td>
								固网
							</td>
							<td>
								指标值
							</td>
							<td>
								单位值
							</td>
							<td>
								指标值计算公式5
							</td>
							<td>
								指标单位5
							</td>
							<td>
								得分计算公式5
							</td>
							<td>
								100
							</td>
						</tr>
						<tr>
							<td>
								移动网
							</td>
							<td>
								指标值
							</td>
							<td>
								单位值
							</td>
							<td>
								指标值计算公式6
							</td>
							<td>
								指标单位6
							</td>
							<td>
								得分计算公式6
							</td>
							<td>
								100
							</td>
						</tr>
						<tr>
							<td rowspan="5">
							</td>
							<td rowspan="5">
								2
							</td>
							<td rowspan="5">
								数据管理
							</td>
							<td colspan="2">
								经分系统月均用户使用量
							</td>
							<td>
								指标值
							</td>
							<td>
								单位值
							</td>
							<td>
								指标值计算公式1
							</td>
							<td>
								指标单位1
							</td>
							<td>
								得分计算公式1
							</td>
							<td>
								100
							</td>
						</tr>
						<tr>
							<td colspan="2">
								数据稽核及时性
							</td>
							<td>
								指标值
							</td>
							<td>
								单位值
							</td>
							<td>
								指标值计算公式1
							</td>
							<td>
								指标单位1
							</td>
							<td>
								得分计算公式1
							</td>
							<td>
								100
							</td>
						</tr>
						<tr>
							<td colspan="2">
								经分参数维护及时性（包括片区参数、竞争对手号段、效能分析渠道任务等）
							</td>
							<td>
								指标值
							</td>
							<td>
								单位值
							</td>
							<td>
								指标值计算公式2
							</td>
							<td>
								指标单位2
							</td>
							<td>
								得分计算公式2
							</td>
							<td>
								100
							</td>
						</tr>
						<tr>
							<td colspan="2">
								渠道营销效能和集团营销效能每月点击率
							</td>
							<td>
								指标值
							</td>
							<td>
								单位值
							</td>
							<td>
								指标值计算公式3
							</td>
							<td>
								指标单位3
							</td>
							<td>
								得分计算公式3
							</td>
							<td>
								100
							</td>
						</tr>
						<tr>
							<td colspan="2">
								经分系统月均用户使用量
							</td>
							<td>
								指标值
							</td>
							<td>
								单位值
							</td>
							<td>
								指标值计算公式4
							</td>
							<td>
								指标单位4
							</td>
							<td>
								得分计算公式4
							</td>
							<td>
								100
							</td>
						</tr>
						<tr>
							<td rowspan="7">
							</td>
							<td rowspan="7">
								3
							</td>
							<td rowspan="7">
								综合管控
							</td>
							<td colspan="2">
								支撑系统运行维护月报上传及时率
							</td>
							<td>
								指标值
							</td>
							<td>
								单位值
							</td>
							<td>
								指标值计算公式1
							</td>
							<td>
								指标单位1
							</td>
							<td>
								得分计算公式1
							</td>
							<td>
								100
							</td>
						</tr>
						<tr>
							<td colspan="2">
								支撑系统运行维护月报完备率
							</td>
							<td>
								指标值
							</td>
							<td>
								单位值
							</td>
							<td>
								指标值计算公式4
							</td>
							<td>
								指标单位4
							</td>
							<td>
								得分计算公式4
							</td>
							<td>
								100
							</td>
						</tr>
						<tr>
							<td colspan="2">
								支撑需求响应时效
							</td>
							<td>
								指标值
							</td>
							<td>
								单位值
							</td>
							<td>
								指标值计算公式4
							</td>
							<td>
								指标单位4
							</td>
							<td>
								得分计算公式4
							</td>
							<td>
								100
							</td>
						</tr>
						<tr>
							<td colspan="2">
								前台业务人员培训覆盖率
							</td>
							<td>
								指标值
							</td>
							<td>
								单位值
							</td>
							<td>
								指标值计算公式4
							</td>
							<td>
								指标单位4
							</td>
							<td>
								得分计算公式4
							</td>
							<td>
								100
							</td>
						</tr>
						<tr>
							<td colspan="2">
								操作差错率
							</td>
							<td>
								指标值
							</td>
							<td>
								单位值
							</td>
							<td>
								指标值计算公式4
							</td>
							<td>
								指标单位4
							</td>
							<td>
								得分计算公式4
							</td>
							<td>
								100
							</td>
						</tr>
						<tr>
							<td colspan="2">
								投诉处理闭环处理能力
							</td>
							<td>
								指标值
							</td>
							<td>
								单位值
							</td>
							<td>
								指标值计算公式4
							</td>
							<td>
								指标单位4
							</td>
							<td>
								得分计算公式4
							</td>
							<td>
								100
							</td>
						</tr>
						<tr>
							<td colspan="2">
								维护作业计划执行情况
							</td>
							<td>
								指标值
							</td>
							<td>
								单位值
							</td>
							<td>
								指标值计算公式4
							</td>
							<td>
								指标单位4
							</td>
							<td>
								得分计算公式4
							</td>
							<td>
								100
							</td>
						</tr>
						<tr>
							<td rowspan="2">
							</td>
							<td rowspan="2">
								4
							</td>
							<td rowspan="2">
								网络及终端安全
							</td>
							<td colspan="2">
								集团安全通报
							</td>
							<td>
								指标值
							</td>
							<td>
								单位值
							</td>
							<td>
								指标值计算公式1
							</td>
							<td>
								指标单位1
							</td>
							<td>
								得分计算公式1
							</td>
							<td>
								100
							</td>
						</tr>
						<tr>
							<td colspan="2">
								终端防病毒软件安装率
							</td>
							<td>
								指标值
							</td>
							<td>
								单位值
							</td>
							<td>
								指标值计算公式4
							</td>
							<td>
								指标单位4
							</td>
							<td>
								得分计算公式4
							</td>
							<td>
								100
							</td>
						</tr>
						<tr>
						<tr>
							<td>
							</td>
							<td>
								5
							</td>
							<td>
								专项工作
							</td>
							<td colspan="2">
								IT专项工作完成率
							</td>
							<td>
								指标值
							</td>
							<td>
								单位值
							</td>
							<td>
								指标值计算公式1
							</td>
							<td>
								指标单位1
							</td>
							<td>
								得分计算公式1
							</td>
							<td>
								100
							</td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
	</body>
</html>
